### ISSUE TITLE
Allo houston ?

### ISSUE THREAD

**Issue by LaurentDardenne** [LxLeChat/ConvertToPSClass#2]
Salut :-) ,
je viens de trouver ton module et le problème que tu soumets, autour de la création d'objet imbriqué :
```Powershell
Class MyCustomObject {
        [pattern[]]$pattern
```
Le problème avant qu'il soit technique me semble dû au fait qu'à partir d'un tableau d'objet, contenant des PsCustomObject, tu souhaites recréer une classe C# (CLR) qui restreint la classe PsCustomObject (DLR pour PS windows >= v3).  (Pour Powershell le choix fait est d'étendre une classe C#).
Pour créer une telle classe, il faudrait récupérer toutes les propriétés de chaque PsCustomObject et les ajouter dans la définition de classe. Mais, dans cet exemple rien ne dit qu'une propriété de même nom soit toujours du même type ( sauf si dans ce cas on utilise Object).
Voir ton exemple avec https://json2csharp.com/

On aura donc une classe fourre tout qui s'éloigne un peu de l'objectif de base de la notion de classe qui est, il me semble, de spécialiser/cloisonner.

Ensuite le ConvertFrom-Json renvoie un PsCustomObject ayant une propriété pattern de type [Object[]] qui contient des PSCustomObject. On ne connait pas le type de chaque élément du tableau. On suppose qu'ils sont du même type ou ont la même structure.
D'émettre un warning pour ces cas serait préférable.

**Comment by LxLeChat** [comment]
salut @LaurentDardenne, je viens juste de voir ton issue et ta clôture xD (désolé j'ai pas trop touché github ces derniers temps ! )

Il faut que je rematte le code, (jai un peu laché quand j'ai vu que doug finke avait fait ça il y a déjà pas mal d'années ... -_-)
il me semble que dans un tableau d'objet, je prends le premier élément, et l'objet classe est crée à partir de cet élément, donc si le deuxième élément a un propriété supplémentaire c'est mort ...

en gros il faudrait que je m'assure que chaque élément à bien le même nombre de propriété ( et du même type) et si c'est pas le cas, ajouté les propriétés manquantes ...
Je crois que je ne l'avais pas fait pour des raisons de performances .. imagine un json avec un tableau de 10000 éléments ... ça va être looooooOong. 

Pour ma problématique je m'accommodais du fait de trouver l'erreur et d'ajouter la propriété manuellement.
```powershell
$MyEntry.Properties += [Property]::new("MyNewProperty","String",$True)
```
on directement à la main dans mon éditeur

**Comment by LaurentDardenne** [comment]
>>But each object does not have the same properties. 

Ce ne peut donc pas être la même classe...

>>il faudrait que je m'assure

Peut être délégué cette charge à l'utilisateur, lui seul sait ce qu'il manipule.
Voir  _discriminator feature_  ici https://prasanthmj.github.io/typescript/serialize-javascript-objects/

**Comment by LxLeChat** [comment]
exactement c'est pour ça que par défaut qd tu convertto-psclass ça sort un objet que tu peux explorer, ajouter des propriétés éventuellement, ou les modifier.

Délégué cette tache à l'utilisateur me semble "normal"
après qd tu décides de faire le -AsString (qui n'est pas obligatoire), on remove les duplicats de classes, je pourrais mettre un warning en expliquant ce qui est remove. Je pourrais aussi taguer les classes en doublons avec un simple ``classname_n`` quand on  fait le tostring

**Comment by LaurentDardenne** [comment]
Je ne suis pas sûr de comprendre le dernier paragraphe.

Dans ton exemple le tableau est de type Pattern, si les 'définitions' sont différentes peut être faut-il s'appuyer sur [l'héritage de classe](https://stackoverflow.com/questions/30240619/c-sharp-array-of-objects-with-inheritance).
Cela resterait cohérent.

Il existe aussi en C# les tuples (_La fonctionnalité tuples fournit une syntaxe concise pour regrouper plusieurs éléments de données dans une structure de données légère._) ou les classes anonyme (_Les types anonymes permettent d'encapsuler un ensemble de propriétés en lecture seule dans un unique objet sans avoir à définir explicitement un type._ ). Ce qui me semble être ici le [Darracq](https://fr.wiktionary.org/wiki/darracq) de la POO ;-)

Donc dans ce cas et pour ceci : 
>>I made this because i was tired to to convert json into PS Classes manually,

il resterait , si j'ai bien compris, à renommer la hiérarchie de classes (_classname_n_) dans le code générer.
Cela reste une supposition n'ayant pas codé cette approche.
